### ISSUE TITLE
配置都是错的,好像不能用

### ISSUE THREAD

**Issue by Zwenjie** [0851/wepy-plugin-usingcomponents#1]

**Comment by 0851** [comment]
晚些时候  我更新一下吧  
不好意思哈

**Comment by 0851** [comment]
已更新说明了  , 这个是用来自动加载原生的usingComponents
就是这种类型的 https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/ 
如果还不行的话 ,可以附带一下详细的配置信息 , 与 错误信息
